services:
    server:
        image: nginx:alpine
        ports:
            - "${SERVER_PORT:-8080}:80"
        volumes:
            - ./:/var/www/html
            - ./public/build/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            MYSQL_HOST: ${DB_HOST:-database}
            MYSQL_DATABASE: ${DB_DATABASE:-database}
            MYSQL_USER: ${DB_USER_NAME:-user}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD:-password}

    php:
        build: ./public/build
        volumes:
            - ./:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
            
    database:
        image: mariadb:11
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD:-password}
            MYSQL_DATABASE: ${DB_DATABASE:-database}
            MYSQL_USER: ${DB_USER_NAME:-user}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD:-password}
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "${DB_PORT:-3307}:3306"

volumes:
    db-data:
